# Generated by Django 4.0.1 on 2022-01-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('movie', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='группа мышц')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counter', models.IntegerField(verbose_name='подходы')),
                ('replay', models.IntegerField(verbose_name='повторения')),
                ('weight', models.IntegerField(verbose_name='вес')),
                ('comment', models.TextField(verbose_name='комментарии')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.exercises')),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.muscles'),
        ),
    ]
