# Generated by Django 4.0.1 on 2022-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name': 'упражнение', 'verbose_name_plural': 'упражнения'},
        ),
        migrations.AlterModelOptions(
            name='muscles',
            options={'verbose_name': 'группа мышц', 'verbose_name_plural': 'группы мышц'},
        ),
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='movie',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='muscle',
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle',
            field=models.ManyToManyField(to='mainapp.Muscles'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='вес'),
        ),
    ]
