# Generated by Django 4.0.1 on 2022-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_planuser_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuser',
            name='plan_date',
            field=models.DateField(default='2022-02-01'),
            preserve_default=False,
        ),
    ]
