# Generated by Django 4.0.1 on 2022-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbody',
            name='data_parameter',
        ),
        migrations.AlterField(
            model_name='datauserparameters',
            name='data',
            field=models.IntegerField(null=True),
        ),
    ]
