# Generated by Django 4.0.1 on 2022-01-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_userbody_data_parameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datauserparameters',
            options={'verbose_name': 'данные параметра тела пользователя', 'verbose_name_plural': 'данные параметра тела пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'verbose_name': 'план пользователь', 'verbose_name_plural': 'планы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usersite',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
